### ISSUE TITLE
Patches missing?

### ISSUE THREAD

**Issue by CKDProductions** [philwinkle/Philwinkle_AppliedPatches#10]
Hey there. Great idea for a module. Love it!

I have been applying patches to some clients via FTP, since I don't have access to SSH on certain systems. I've been using solutions such as http://magentary.com/kb/apply-supee-5344-and-supee-1533-without-ssh/. I've noticed that on the servers I've applied your module to, I'm seeing SUPEE-1533 installed, but not SUPEE-5344, even though I've used the combined files as per the link above to apply both. Any idea why one would show as installed, but not the other? Thanks!

**Comment by philwinkle** [comment]
As per the docs, if you do not retain and upload the app/etc/applied.patches.list file then this module has no way to know. As you're using FTP to deploy changes my guess is that you're not allowing your system to append updates to this file, and therefore you show no patches in the Admin.

This is exactly how the Magento EE functionality works as well; both my module and theirs inspect that file for a list of running changes to the site via the patch system. Thanks.

**Comment by CKDProductions** [comment]
Ah right. My bad, I read that and still didn't put it together. Thanks!
