### ISSUE TITLE
Reverted patches also showing up

### ISSUE THREAD

**Issue by dvdmierden** [philwinkle/Philwinkle_AppliedPatches#11]
After reverting a patch (and re-patching, and re-reverting ..) all references show up:

`Magento ver. 1.9.0.1 SUPEE-1533, SUPEE-5344, SUPEE-5994, SUPEE-6285, SUPEE-6285, SUPEE-6285, SUPEE-6285, SUPEE-6285`

**Comment by philwinkle** [comment]
Fixed in #13
