### ISSUE TITLE
Odd error on one of my deployments

### ISSUE THREAD

**Issue by CKDProductions** [philwinkle/Philwinkle_AppliedPatches#14]
I have installed your module on a dozen clients. They all work great except for one, I am seeing these errors in the error log (I replaced the website with xxx but otherwise this is the error):

2015-08-08T01:24:12+00:00 ERR (3): Warning: include(Mage/Appliedpatches/Helper/Data.php): failed to open stream: No such file or directory  in /chroot/home/xxx/xxx.com/html/lib/Varien/Autoload.php on line 93
2015-08-08T01:24:12+00:00 ERR (3): Warning: include(Mage/Appliedpatches/Helper/Data.php): failed to open stream: No such file or directory  in /chroot/home/xxx/xxx.com/html/lib/Varien/Autoload.php on line 93
2015-08-08T01:24:12+00:00 ERR (3): Warning: include(): Failed opening 'Mage/Appliedpatches/Helper/Data.php' for inclusion (include_path='/chroot/home/xxx/xxx.com/html/app/code/local:/chroot/home/xxx/xxx.com/html/app/code/community:/chroot/home/xxx/xxx.com/html/app/code/core:/chroot/home/xxx/xxx.com/html/lib:.:/usr/share/pear:/usr/share/php')  in /chroot/home/xxx/xxx.com/html/lib/Varien/Autoload.php on line 93

Not sure why it's looking in Mage? I installed it the same as all the other deployments. This is a 1.7.0.2 install in case that matters at all. Thanks!

**Comment by philwinkle** [comment]
Is the module fully up to date? It sounds as if there is a problem with a
missing helper. When helpers are missing Magento falls back to Mage.

**Comment by philwinkle** [comment]
Any update?

On Sat, Aug 8, 2015 at 9:57 AM, Phillip Jackson philwinkle@gmail.com
wrote:

> Is the module fully up to date? It sounds as if there is a problem with a
> missing helper. When helpers are missing Magento falls back to Mage.
> On Aug 7, 2015 9:33 PM, "Kevin" notifications@github.com wrote:
> 
> > I have installed your module on a dozen clients. They all work great
> > except for one, I am seeing these errors in the error log (I replaced the
> > website with xxx but otherwise this is the error):
> > 
> > 2015-08-08T01:24:12+00:00 ERR (3): Warning:
> > include(Mage/Appliedpatches/Helper/Data.php): failed to open stream: No
> > such file or directory in /chroot/home/xxx/
> > xxx.com/html/lib/Varien/Autoload.php on line 93
> > 2015-08-08T01:24:12+00:00 ERR (3): Warning:
> > include(Mage/Appliedpatches/Helper/Data.php): failed to open stream: No
> > such file or directory in /chroot/home/xxx/
> > xxx.com/html/lib/Varien/Autoload.php on line 93
> > 2015-08-08T01:24:12+00:00 ERR (3): Warning: include(): Failed opening
> > 'Mage/Appliedpatches/Helper/Data.php' for inclusion
> > (include_path='/chroot/home/xxx/
> > xxx.com/html/app/code/local:/chroot/home/xxx/xxx.com/html/app/code/community:/chroot/home/xxx/xxx.com/html/app/code/core:/chroot/home/xxx/xxx.com/html/lib:.:/usr/share/pear:/usr/share/php')
> > in /chroot/home/xxx/xxx.com/html/lib/Varien/Autoload.php on line 93
> > 
> > Not sure why it's looking in Mage? I installed it the same as all the
> > other deployments. This is a 1.7.0.2 install in case that matters at all.
> > Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/philwinkle/Philwinkle_AppliedPatches/issues/14.

## 

Follow me on Twitter - @philwinkle
Friend me on Facebook - http://www.facebook.com/philwinkle

**Comment by CKDProductions** [comment]
Sorry for the delay. I installed the latest version of the module, and I get the same issue. Odd, since it's  working on my other 1.7.0.2 deployments. I haven't had time to look further into it though as of yet.

**Comment by philwinkle** [comment]
Dead issue - closing due to age.
