### ISSUE TITLE
shows a little too much...

### ISSUE THREAD

**Issue by hpvd** [philwinkle/Philwinkle_AppliedPatches#3]
The idea for this extension is awesome!
Works great and shows all patches.

One tiny thing could be optimized: on some installations it shows a little too much  information. Please see attachment.
The yellow highlighting was done in the picture..

![2015-05-21_11h45_46](https://cloud.githubusercontent.com/assets/5681880/7746124/4f8f63d6-ffb0-11e4-999b-2650f4f54212.png)

Installation details for this example:
magento CE 1.9.1,
PHP 5.5,
FreeBSD
extension copied directly without modman

**Comment by philwinkle** [comment]
I believe the issue here is that line endings in FreeBSD don't work the
same way.

Can you give me the raw unedited version of your applied.patches.list?

On Thu, May 21, 2015 at 5:56 AM, hpvd notifications@github.com wrote:

> The idea for this extension is awesome!
> Works great and shows all patches.
> 
> On our installation magento CE 1.9.1, PHP 5.5, FreeBSB
> it only shows a little to much
> [image: 2015-05-21_11h45_46]
> https://cloud.githubusercontent.com/assets/5681880/7746124/4f8f63d6-ffb0-11e4-999b-2650f4f54212.png
> information.
> 
> Please attachment.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/philwinkle/Philwinkle_AppliedPatches/issues/3.

## 

Follow me on Twitter - @philwinkle
Friend me on Facebook - http://www.facebook.com/philwinkle

**Comment by hpvd** [comment]
thanks for getting back that fast!

The list really looks a little strange..
it contains things like:

```
2014-10-06 15:42:18 UTC | SUPEE-1533 | EE_1.13 | v1 | _ | n/a | SUPEE-1533_EE_1.13_v1.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php
|index c698108..6e256bb 100644
|--- app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php
|+++ app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php
--------------------------
Patching file app/code/core/Mage/Adminhtml/Block/Dashboard/Graph.php using Plan A...
Hunk #1 succeeded at 444.
```

just post you a mail with the complete original file

**Comment by hpvd** [comment]
works perfect! Many thanks!

![2015-05-26_19h31_11](https://cloud.githubusercontent.com/assets/5681880/7818753/dce36f3a-03dd-11e5-960e-7628a2e6c960.png)
