### ISSUE TITLE
Fatal error: Magento ver. 1.9.1.1  Fatal error: Class 'Philwinkle_AppliedPatches_Helper_Data' not found

### ISSUE THREAD

**Issue by dvdmierden** [philwinkle/Philwinkle_AppliedPatches#8]
After uploading all files, I see:
Magento ver. 1.9.1.1 
Fatal error: Class 'Philwinkle_AppliedPatches_Helper_Data' not found in /home/users/smauiftp/app/Mage.php on line 547

Any idea?
Thanks!
Daniel

**Comment by philwinkle** [comment]
I'm not getting that on 1.9.1.1 - do you have a diff of the commit before you put the module on your store? How did you install? Modman? 

Any more information would be helpful. Thanks!

**Comment by philwinkle** [comment]
Closing for now due to no response. I'm happy to reopen should you come back with some more info so we can troubleshoot. Thanks!

**Comment by dvdmierden** [comment]
Sorry late reply :-)

Unfortunately, no diff. 
I just copied your /app directory into the magento /app and refreshed the cache.

**Comment by dvdmierden** [comment]
Actually, the problem's gone! I removed the extension, re-uploaded it, and everything works fine!

Cheers
